# Generated by Django 3.2 on 2021-05-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='To',
            field=models.DateField(blank=True, null=True),
        ),
    ]
