# Generated by Django 3.2 on 2021-08-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterbuyhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
