# Generated by Django 3.2 on 2021-04-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tools',
            name='Title',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
