# Generated by Django 3.2 on 2021-05-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Details', models.CharField(max_length=2000)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='')),
                ('Published_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
