# Generated by Django 3.2 on 2021-09-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='subRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Names', models.CharField(blank=True, max_length=255, null=True)),
                ('Message', models.TextField(blank=True)),
                ('Subscriptions', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('phonenumber', models.CharField(blank=True, max_length=255, null=True)),
                ('Province', models.CharField(blank=True, max_length=255, null=True)),
                ('District', models.CharField(blank=True, max_length=255, null=True)),
                ('Sector', models.CharField(blank=True, max_length=255, null=True)),
                ('Cell', models.CharField(blank=True, max_length=255, null=True)),
                ('Language', models.CharField(blank=True, max_length=255, null=True)),
                ('service', models.CharField(blank=True, max_length=255, null=True)),
                ('send_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
