# Generated by Django 3.2 on 2021-08-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_waterbuyhistory_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionspayment',
            name='Paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionspayment',
            name='PaidMonth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
