# Generated by Django 3.2 on 2021-04-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_tools_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptions',
            name='LastDateofPayment',
        ),
        migrations.AddField(
            model_name='subscriptionstools',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
