# Generated by Django 3.2 on 2021-04-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210428_0744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionstools',
            name='Amount',
        ),
        migrations.AddField(
            model_name='tools',
            name='Amount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
