# Generated by Django 3.2 on 2021-05-10 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_subscriptions_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.category'),
        ),
    ]
