# Generated by Django 3.2 on 2021-04-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210428_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meters',
            name='Meternumber',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
