# Generated by Django 3.2 on 2021-05-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Details',
            field=models.TextField(blank=True),
        ),
    ]
