# Generated by Django 3.2 on 2021-09-19 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_subrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subrequest',
            name='service',
        ),
    ]
