# Generated by Django 3.2 on 2021-09-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_subrequest_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='customer_exception',
            field=models.BooleanField(default=False),
        ),
    ]
