# Generated by Django 3.2 on 2021-04-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210430_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tools',
            name='Amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
