# Generated by Django 3.2 on 2021-05-24 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_blog_details'),
        ('users', '0003_auto_20210524_1137'),
    ]

    operations = [
    ]
