# Generated by Django 3.2 on 2021-04-28 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_meters_meternumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Meternumber',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.meters'),
        ),
    ]
