# Generated by Django 3.2 on 2021-09-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_subscriptions_customer_exception'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
