# Generated by Django 3.2 on 2021-04-30 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_request'),
        ('users', '0004_alter_tools_amount'),
    ]

    operations = [
    ]
