# Generated by Django 3.2 on 2021-05-31 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='Message',
            field=models.CharField(max_length=200),
        ),
    ]
