# Generated by Django 3.2 on 2021-05-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_merge_0002_request_0004_alter_tools_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptions',
            name='Totalamount',
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
