# Generated by Django 3.2 on 2021-10-08 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210926_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tools',
            name='CategoryID',
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('inches', models.CharField(blank=True, max_length=100, null=True)),
                ('users', models.CharField(blank=True, max_length=100, null=True)),
                ('Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.category')),
            ],
        ),
        migrations.AddField(
            model_name='tools',
            name='System',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.system'),
        ),
    ]
