# Generated by Django 3.2 on 2021-06-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_subscriptions_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='To',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
