# Generated by Django 3.2 on 2021-06-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_subscriptions_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='Idnumber',
        ),
        migrations.AddField(
            model_name='request',
            name='Message',
            field=models.TextField(blank=True),
        ),
    ]
