# Generated by Django 3.2 on 2021-10-09 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_tools_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system',
            name='users',
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='System',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.system'),
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='users',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
