# Generated by Django 3.2 on 2021-06-20 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_request_replied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Phone',
        ),
    ]
