# Generated by Django 3.2 on 2021-10-13 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_orderitemtool_ordertools_toolshippingaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subrequest',
            name='Subscriptions',
        ),
        migrations.RemoveField(
            model_name='subrequest',
            name='category',
        ),
    ]
