# Generated by Django 3.2 on 2021-10-15 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20211013_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionstools',
            name='ToolID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.tools'),
        ),
    ]
