# Generated by Django 3.2 on 2021-10-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20211015_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='Tools',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
