# Generated by Django 3.2 on 2021-07-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='service',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
