# Generated by Django 3.2 on 2021-07-18 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_request_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tools',
            name='SerialNumber',
        ),
    ]
