# Generated by Django 3.2 on 2021-10-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_subscriptions_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='Total',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
