# Generated by Django 3.2 on 2021-07-19 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_waterbuyhistory_expired_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterbuyhistory',
            name='NumberofLitres',
        ),
    ]
