# Generated by Django 3.2 on 2021-07-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_waterbuyhistory_expired_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
