# Generated by Django 3.2 on 2021-10-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_subscriptions_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='Downpayment',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
