# Generated by Django 3.2 on 2021-07-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20210719_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='reply',
            field=models.TextField(blank=True, default='Please wait for the response', null=True),
        ),
    ]
