# Generated by Django 3.2 on 2021-07-19 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_waterbuyhistory_numberoflitres'),
        ('users', '0018_alter_request_reply'),
    ]

    operations = [
    ]
