# Generated by Django 3.2 on 2021-10-27 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_subscriptions_downpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='From',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='To',
            field=models.DateField(blank=True, null=True),
        ),
    ]
