# Generated by Django 3.2 on 2021-11-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_subscriptions_tools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='TotalBalance',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
    ]
