# Generated by Django 3.2 on 2021-07-29 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_waterbuyhistory_meternumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterbuyhistory',
            name='Meternumber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.meters'),
        ),
    ]
