# Generated by Django 3.2 on 2021-11-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20211112_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='discount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='discount1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
