# Generated by Django 3.2 on 2021-11-09 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_subscriptions_system2'),
        ('users', '0024_alter_subscriptions_totalbalance'),
    ]

    operations = [
    ]
