# Generated by Django 3.2 on 2021-08-03 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_subscriptions_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='CustomerID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
        migrations.AlterField(
            model_name='subscriptionspayment',
            name='SubscriptionsID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.subscriptions'),
        ),
    ]
