# Generated by Django 3.2 on 2021-11-16 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20211112_1438'),
        ('users', '0025_merge_20211109_1542'),
    ]

    operations = [
    ]
