# Generated by Django 3.2 on 2021-08-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20210803_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMeter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('meter', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
