# Generated by Django 3.2 on 2021-08-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20210803_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Language',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
