# Generated by Django 3.2 on 2021-08-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_customer_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='Language',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
