# Generated by Django 3.2 on 2021-08-04 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_customermeter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customermeter',
            old_name='customer',
            new_name='customer_phone',
        ),
    ]
