# Generated by Django 3.2 on 2021-08-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_request_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Disable',
            field=models.BooleanField(default=False),
        ),
    ]
