# Generated by Django 3.2 on 2021-08-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_rename_customer_customermeter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermeter',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customermeter',
            name='meter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
