# Generated by Django 3.2.9 on 2022-02-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_order_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertools',
            name='delivery',
            field=models.BooleanField(default=False),
        ),
    ]
