# Generated by Django 3.2.9 on 2022-02-05 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_ordertools_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Meternumber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.meters'),
        ),
    ]
