# Generated by Django 3.2.9 on 2022-02-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_waterbuyhistory_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='subrequest',
            name='replied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subrequest',
            name='reply',
            field=models.TextField(blank=True, default='Please wait for the response', null=True),
        ),
        migrations.AddField(
            model_name='subrequest',
            name='techdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subrequest',
            name='techname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subrequest',
            name='techphone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
