# Generated by Django 3.2.9 on 2022-02-16 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_alter_customer_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
    ]
