# Generated by Django 3.2.9 on 2022-05-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_request_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterbuyhistory',
            name='TransactionID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
