# Generated by Django 3.2.10 on 2022-08-20 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_otherpayment'),
        ('users', '0043_subrequest_pending'),
    ]

    operations = [
    ]
