# Generated by Django 3.2.10 on 2022-08-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_merge_0043_otherpayment_0043_subrequest_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherpayment',
            name='PaymentType',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionspayment',
            name='PaymentType',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='waterbuyhistory',
            name='PaymentType',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
