# Generated by Django 3.2.10 on 2022-09-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_auto_20220826_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionspayment',
            name='TransID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
