# Generated by Django 3.2.10 on 2022-09-08 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_subscriptionspayment_transid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HOTELLIST',
        ),
        migrations.AddField(
            model_name='subrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
