# Generated by Django 3.2.10 on 2022-09-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_auto_20220908_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterbuyhistory',
            name='TransactionID',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
