# Generated by Django 3.2.10 on 2023-02-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_alter_waterbuyhistory_transactionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customerType',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
