# Generated by Django 3.2.10 on 2023-03-07 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_customer_customertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='changeDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
