# Generated by Django 3.2.10 on 2024-06-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_user_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterbuyhistory',
            name='IsPaid',
            field=models.BooleanField(default=True),
        ),
    ]
